PUT http://localhost:8080/api/upper/ruoshui
Content-Type: application/json; charset=utf-8
Accept: application/json

{ "consumer": 23 }

###
PUT http://localhost:8080/api/upper/ruoshui
Content-Type: application/x-yaml; charset=utf-8
Accept: application/x-yaml

{}
###

PUT http://localhost:8080/api/upper/ruoshui
Content-Type: application/x-yaml; charset=utf-8
Accept: application/x-yaml

consumer:
  src_property:
    PGHOST: 192.168.119.137
    PGPORT: "5432"
    PGDBNAME: postgres
    password: postgres
  get_snapshot: false
producer:
  kfk_property:
    bootstrap.servers: 192.168.119.137:9092
    acks: all
  target_topic: ruoshui-upper

###

# TODO: 尚未支持XML的响应格式.
PUT http://localhost:8080/api/upper/ruoshui
Content-Type: application/x-yaml; charset=utf-8
Accept: application/xml

{ "consumer": 23 }

###

DELETE http://localhost:8080/api/upper/ruoshui
Accept: application/json

###

GET http://localhost:8080/api/upper/ruoshui
# Accept: application/json

###

POST http://localhost:8080/api/upper/ruoshui/snapshot
Content-Type: application/x-yaml; charset=utf-8
Accept: application/x-yaml

src_property:
  PGHOST: 192.168.119.137
  PGPORT: 5432
  PGDBNAME: postgres
  password: postgres

###
