spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  groovy:
    template:
      check-template-location: false
  output:
    ansi:
      enabled: always
server.servlet.context-path: /